apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-notifications
  namespace: lunaris-mcs
  labels:
    app: push-notifications
spec:
  selector:
    matchLabels:
      app: push-notifications
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: push-notifications
    spec:
      containers:
      - name: push-notifications
        imagePullPolicy: Always # TODO: Change to IfNotPresent in production
        image: raducualexandrumircea/nodejs-ts-mcs-arm64:v1
        # TODO: Changes resources in production
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        # TODO: Add redinessProbe in production
        #readinessProbe:
        #  httpGet:
        #    path: /health/check
        #    port: 8080
        #  initialDelaySeconds: 10
        #  failureThreshold: 5
        #  periodSeconds: 10
        envFrom:
          - configMapRef:
              name: push-notifications-configmap
          - secretRef:
              name: shared-secret
          - configMapRef:
              name: shared-configmap
        ports:
        - containerPort: 8080
          name: main-port
        volumeMounts:
        - mountPath: /usr/src/app # TODO: Remove in production
          name: push-notifications-hostpath
      volumes:
      - name: push-notifications-hostpath # TODO: Remove in production
        hostPath:
          path: "/mnt/Users/alexmircea/Desktop/PersonalProjects/Lunaris/dev/mcs/push-notifications"
          type: Directory
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-hub-secret
