apiVersion: v1
kind: Service
metadata:
  name: push-notifications-service
  namespace: lunaris-mcs
spec:
  selector:
    app: push-notifications
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: push-notifications-service
    protocol: TCP
    port: 80
    targetPort: 8080
