apiVersion: v1
kind: Service
metadata:
  name: redis-socket-service
  namespace: lunaris-databases
spec:
  selector:
    app: redis-socket
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: redis-socket-service
    protocol: TCP
    port: 6379
    targetPort: 6379
