apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: lunaris-databases
spec:
  selector:
    app: mongodb
  #type: NodePort
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: mongodb-service
    protocol: TCP
    port: 27017
    targetPort: 27017
    #nodePort: 31000
