apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: lunaris-management-tools
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: mongo-express-service
    protocol: TCP
    port: 80
    targetPort: 8081
