apiVersion: v1
kind: Service
metadata:
  name: fees-service
  namespace: lunaris-mcs
spec:
  selector:
    app: fees
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: fees-service
    protocol: TCP
    port: 80
    targetPort: 8080
