apiVersion: v1
kind: PersistentVolume
metadata:
  name: email-templates-pv-vol
  namespace: lunaris-mcs
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  claimRef:
    name: email-templates-pvc
    namespace: lunaris-mcs
  capacity:
    storage: 150Kb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/Lunaris/volumes/email-templates"
