apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-templates-pvc
  namespace: lunaris-mcs
spec:
  storageClassName: microk8s-hostpath
  volumeName: email-templates-pv-vol
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Ki
