apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: lunaris-mcs
spec:
  selector:
    app: login
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: login-service
    protocol: TCP
    port: 80
    targetPort: 8080
