apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy
  namespace: lunaris-frontends
  labels:
    app: buy
spec:
  selector:
    matchLabels:
      app: buy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: buy
    spec:
      containers:
      - name: buy
        imagePullPolicy: Always # TODO: Change to IfNotPresent in production
        image: raducualexandrumircea/lunaris-dev-frontend-buy:v1
        # TODO: Changes resources in production
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 4200
          name: buy
        volumeMounts:
        - mountPath: /usr/src/app/src # TODO: Remove in production
          name: buy-hostpath
      volumes:
      - name: buy-hostpath # TODO: Remove in production
        hostPath:
          path: "/mnt/Users/alexmircea/Desktop/PersonalProjects/Lunaris/dev/frontends/buy/src"
          type: Directory
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-hub-secret
