apiVersion: v1
kind: Service
metadata:
  name: buy-service
  namespace: lunaris-frontends
spec:
  selector:
    app: buy
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: buy-service
    protocol: TCP
    port: 80
    targetPort: 4200
