apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: lunaris-frontends
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        imagePullPolicy: Always # TODO: Change to IfNotPresent in production
        image: raducualexandrumircea/angular-frontend-arm64:v1
        # TODO: Changes resources in production
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 4200
          name: app
        volumeMounts:
        - mountPath: /usr/src/app # TODO: Remove in production
          name: app-hostpath
      volumes:
      - name: app-hostpath # TODO: Remove in production
        hostPath:
          path: "/home/ubuntu/Lunaris/dev/frontends/app"
          type: Directory
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-hub-secret
