apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: lunaris-frontends
spec:
  selector:
    app: app
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: app-service
    protocol: TCP
    port: 80
    targetPort: 4200
