apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lunaris-databases
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        imagePullPolicy: IfNotPresent
        image: mysql:8.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 5000Mi
        envFrom:
          - secretRef:
              name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pv
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
      restartPolicy: Always
