apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: lunaris-databases
spec:
  selector:
    app: mysql
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: mysql-service
    protocol: TCP
    port: 3306
    targetPort: 3306
