apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: lunaris-mcs
  labels:
    app: clamav
spec:
  selector:
    matchLabels:
      app: clamav
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: clamav/clamav:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 3310
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: clamav-configmap
        ports:
        - containerPort: 3310
          name: clamav-1
        - containerPort:  7357
          name: clamav-2
        volumeMounts:
        - mountPath: /var/lib/clamav
          name: clamav-volume
      volumes:
      - name: clamav-volume
        persistentVolumeClaim:
          claimName: clamav-pvc
      restartPolicy: Always
