apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-pvc
  namespace: lunaris-mcs
spec:
  storageClassName: microk8s-hostpath
  volumeName: clamav-pv-vol
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
