kind: ConfigMap
apiVersion: v1
metadata:
  name: phpmyadmin-configmap
  namespace: lunaris-management-tools
data:
  PMA_HOST: 'mysql-service.clvber-dev'
  PMA_PORT: '3306'
  PMA_ABSOLUTE_URI: 'https://super-admin.lunarisapp.com/userphpmyadmin'
