apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-mysql
  namespace: lunaris-management-tools
  labels:
    app: phpmyadmin-mysql
spec:
  selector:
    matchLabels:
      app: phpmyadmin-mysql
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin-mysql
    spec:
      containers:
      - name: phpmyadmin-mysql
        imagePullPolicy: IfNotPresent
        image: phpmyadmin:latest
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 300Mi
        envFrom:
          - configMapRef:
              name: phpmyadmin-mysql-configmap
        ports:
        - containerPort: 80
          name: phpmyadmin
      restartPolicy: Always
