apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: lunaris-management-tools
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        imagePullPolicy: IfNotPresent
        image: phpmyadmin/phpmyadmin:latest
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
          - configMapRef:
              name: phpmyadmin-configmap
        ports:
        - containerPort: 80
          name: phpmyadmin
      restartPolicy: Always
